#!/bin/sh

set -e

xrandr --dpi 96
xrdb -merge -I$HOME $HOME/.Xresources-lowdpi

xrandr \
  --output eDP1 --mode 2560x1700 --pos 0x0 \
  --output DP1 --off \
  --output DP2 --mode 2560x1440 --primary --right-of eDP1 \
  --output HDMI1 --off \
  --output HDMI2 --off \
  --output VIRTUAL1 --off
