#!/usr/bin/env bash

set -e -u -x

if [ -z "$CONTAINER_ID" ]; then
  echo "This script must be run from inside distrobox container."
  exit 1
fi

cd $HOME

# install basics, the rest of it is in $HOME already
sudo dnf install -y fish util-linux-user
chsh -s $(which fish) $(whoami)

# for tree-sitter auto-compilation
sudo dnf install -y gcc

# faster grep
sudo dnf install -y ripgrep

# basic CLI ops utils
sudo dnf install -y htop
# exporting is weird since it runs in a separate context than intended
# distrobox-export --bin /usr/bin/htop --export-path ~/.bin

# install neovim to the host
sudo dnf install -y neovim
distrobox-export --bin /usr/bin/nvim --export-path ~/.bin
ln -sf $HOME/.bin/nvim $HOME/.bin/vim

# install Go
go_version=1.22.1
if ! test -d /usr/local/go || /usr/local/go/bin/go version | grep -v go${go_version}; then
  curl -sSL https://go.dev/dl/go${go_version}.linux-amd64.tar.gz | \
    sudo tar -C /usr/local -xzf -
fi

# use host Docker
sudo ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker

# install bat
sudo dnf install -y bat

# for copilot
sudo dnf install -y nodejs

# for gRPC + Go tooling
sudo dnf install -y protobuf-compiler
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# language servers
go install github.com/nametake/golangci-lint-langserver@latest

# Node tooling
if ! which pnpm 2>&1 > /dev/null; then
  curl -fsSL https://get.pnpm.io/install.sh | sh -
fi
pnpm install -g typescript-language-server typescript
