#!/usr/bin/env bash

# install basics, the rest of it is in $HOME already
sudo dnf install -y neovim fish util-linux-user
chsh -s $(which fish) $(whoami)

# for tree-sitter auto-compilation
sudo dnf install -y gcc

# install neovim to the host
distrobox-export --bin $(which nvim) --export-path ~/.bin
ln -sf $HOME/.bin/nvim $HOME/.bin/vim

# use host Docker
sudo ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker
