#!/bin/bash

set -e -x

if [ "$(id -u)" = "0" ]; then
  echo "do not run as root"
  exit 1
fi

cd $(dirname $0)

function gimme_pacman() {
  sudo pacman --noconfirm --needed -Sy "$@"
}

function gimme_aur() {
  sudo aura --noconfirm --needed -Ay "$@"
}

sudo timedatectl set-ntp true

gimme_pacman base-devel

gimme_pacman stow

gimme_pacman xorg

gimme_pacman pulseaudio pavucontrol
sudo usermod -aG audio $(whoami)

# nouveau driver is super glitchy (missing cursor, janky multi-head), so
# install official nvidia driver instead
if lspci | grep VGA | grep -i nvidia; then
  gimme_pacman nvidia
fi

gimme_pacman xmonad xmonad-contrib xmobar
gimme_aur dmenu-xft

# TODO: better method for detecting laptop
if [ "$(hostname)" = "think" ]; then
  stow xorg-laptop
else
  stow xorg-desktop
fi

stow xmonad

gimme_pacman fish
sudo chsh -s /usr/bin/fish $(whoami)
stow fish

if ! which aura >/dev/null; then
  git clone https://aur.archlinux.org/aura-bin.git /tmp/aura
  pushd /tmp/aura
    makepkg -sri
  popd

  rm -rf /tmp/aura
fi

gimme_pacman termite
gimme_aur ttf-iosevka
stow termite

gimme_aur neovim-git
gimme_pacman python-pip
sudo pip install neovim
if ! [ -e ~/.nvim ]; then
  git clone https://github.com/vito/dot-nvim.git ~/.nvim
fi

mkdir -p ~/bin
stow wrappers

gimme_pacman ruby
stow gem

gem install git-duet
stow git

gimme_pacman mate-themes
stow gtk

gimme_pacman the_silver_searcher

gimme_aur lastpass-cli

gimme_pacman openssh

gimme_pacman go

gimme_aur direnv

gimme_pacman xsel

gimme_aur ttf-ms-fonts otf-texgyre
