#!/bin/bash

set -e -x

cd $(dirname $0)

NEOVIM_CONFIG='https://github.com/vito/dot-nvim.git'

function gimme() {
  sudo apt -y install "$@"
}

# useful for installing .deb with deps with -n; used for Slack install
gimme gdebi

# sync up everything
sudo apt update

# install neovim, + python for plugins, + xclip for copy/paste
gimme \
  neovim \
  python-dev python-pip python3-dev python3-pip \
  xclip

# support for python3 plugins
sudo pip3 install neovim

# set up neovim as vi/vim/editor
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --set vi /usr/bin/nvim
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
sudo update-alternatives --set vim /usr/bin/nvim
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
sudo update-alternatives --set editor /usr/bin/nvim

# bootstrap neovim config (`git pull` on your own)
if ! [ -e ~/.config/nvim ]; then
  git clone "$NEOVIM_CONFIG" ~/.config/nvim --recursive
fi

# config orchestration
gimme stow

# shell
gimme fish
stow fish
sudo chsh -s /usr/bin/fish $(whoami)

# ruby + gem config
gimme ruby
stow gem

# git
gimme git
stow git
GEM_HOME=$HOME/.gems gem install git-duet

# golang
gimme golang
GOPATH=$HOME/go vim --headless +GoInstallBinaries +qa

# postgresql
gimme postgresql
sudo usermod -aG postgres $(whoami)

# create superuser role for current user with empty password
yes "" | sudo su postgres -c "createuser -s -P $(whoami)" || true

# misc tooling
gimme htop silversearcher-ag direnv lastpass-cli pavucontrol curl jq
