#!/bin/bash

set -e -x

# stow is relative to this directory
cd $(dirname $0)

# global assumptions
mkdir -p ~/bin ~/.config

NEOVIM_CONFIG='https://github.com/vito/dot-nvim.git'

function gimme() {
  local name=$(basename $1)
  if brew list | grep "\\<$name\\>"; then
    brew outdated "$name" || brew install "$@"
  else
    brew install "$@"
  fi
}

function gimme_all() {
  for x in "$@"; do
    gimme "$x"
  done
}

function gimme_cask() {
  for x in "$@"; do
    if ! brew cask list | grep "\\<$x\\>"; then
      brew cask install "$x"
    fi
  done
}

# install homebrew
if ! which brew >/dev/null; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# install cask
brew tap caskroom/cask

# install simple config manager
gimme stow

# install and switch to fish
gimme fish
grep "$(which fish)" /etc/shells >/dev/null || sudo sh -c "echo $(which fish) >> /etc/shells"
finger $USER | grep "$(which fish)" >/dev/null || sudo chsh -s "$(which fish)" $(whoami)
stow fish

# install neovim as ~/bin/vim, + python support
gimme_all neovim/neovim/neovim python3
pip3 install neovim
ln -sf "$(which nvim)" ~/bin/vim

# bootstrap neovim config (`git pull` on your own)
if ! [ -e ~/.config/nvim ]; then
  git clone "$NEOVIM_CONFIG" ~/.config/nvim --recursive
fi

# install ruby + sane gem config
gimme ruby
stow gem

# install git + git config + sane git duet
gimme git
stow git
GEM_HOME=$HOME/.gems gem install git-duet

# install golang toolchain
gimme go
GOPATH=$HOME/go nvim --headless +GoInstallBinaries +qa

# install node/elm/etc toolchain
gimme node
npm install -g uglify-js less less-plugin-clean-css elm elm-oracle elm-test

# install postgres
gimme postgresql
ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents

# install phantojs
gimme phantomjs

# install gui livelihood
gimme_cask google-chrome iterm2 slack

# install Onsi's ShiftIt which supports sizing in thirds
if ! [ -e /Applications/ShiftIt.app ]; then
  curl -fsSL https://raw.github.com/onsi/ShiftIt/master/ShiftIt.zip -o /tmp/ShiftIt.zip
  unzip /tmp/ShiftIt.zip -d /Applications
fi

# install cli livelihood
gimme_all jq htop stress direnv the_silver_searcher lastpass-cli
gimme_cask vagrant virtualbox

# install bosh + tooling
gimme cloudfoundry/tap/bosh-cli --without-bosh2
stow bosh
