#!/bin/bash

set -e -x

# global assumptions
mkdir -p ~/bin ~/.config

NEOVIM_CONFIG='https://github.com/vito/dot-nvim.git'

function gimme() {
  for x in "$@"; do
    if brew list | grep "\\<$x\\>"; then
      brew outdated "$x" || brew upgrade "$x"
    else
      brew install "$x"
    fi
  done
}

function gimme_cask() {
  for x in "$@"; do
    if ! brew cask list | grep "\\<$x\\>"; then
      brew cask install "$x"
    fi
  done
}

# install homebrew
if ! which brew >/dev/null; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# install cask
brew tap caskroom/cask

# install simple config manager
gimme stow

# install and switch to fish
gimme fish
grep "$(which fish)" /etc/shells || sudo sh -c "echo $(which fish) >> /etc/shells"
sudo chsh -s "$(which fish)" $(whoami)
stow fish

# install neovim as ~/bin/vim, + python support
gimme neovim/neovim/neovim python3
pip3 install neovim
ln -sf "$(which nvim)" ~/bin/vim

# bootstrap neovim config (`git pull` on your own)
if ! [ -e ~/.config/nvim ]; then
  git clone "$NEOVIM_CONFIG" ~/.config/nvim --recursive
fi

# install ruby + sane gem config
gimme ruby
stow gem

# install git + git config + sane git duet
gimme git
stow git
GEM_HOME=$HOME/.gems gem install git-duet

# install golang toolchain
gimme go
GOPATH=$HOME/go nvim --headless +GoInstallBinaries +qa

# install node/elm/etc toolchain
gimme node
npm install -g uglify-js less less-plugin-clean-css elm elm-oracle elm-test

# install postgres
gimme postgresql
ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents

# install phantojs
gimme phantomjs

# install gui livelihood
gimme_cask google-chrome iterm2 slack

# install cli livelihood
gimme jq htop stress direnv the_silver_searcher
gimme lastpass-cli --with-pinentry --with-doc
gimme_cask vagrant virtualbox
