#!/bin/bash

set -e -u -x

cd $(dirname $0)

# simple config manager
brew install stow

# local executables dir
mkdir -p ~/.local/bin

# setup fish
brew install fish fisher starship direnv
stow -t ~ fish
fish -c 'fisher update'
fish -c 'fisher install rose-pine/fish'

# install rg
brew install ripgrep

# setup go
brew install go

# setup best font
brew install font-iosevka-ss08

# set up ghostty
brew install --cask ghostty
stow -t ~ ghostty

# fzf and friends
brew install bat jq

# configure git
brew install difftastic
./git/configure

# utility kit
stow -t ~ utils

# support holding hjkl
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# disable weird cmd-tab monitor selection
defaults write com.apple.Dock appswitcher-all-displays -bool true

# setup vim
brew install neovim
ln -sf /usr/local/bin/nvim ~/.local/bin/vim

# docker
brew install --cask docker
