#!/bin/bash

set -e -u -x

cd $(dirname $0)

# simple config manager
brew install stow

# local executables dir
mkdir -p ~/bin

# setup fish
brew install fish
stow -t ~ fish
fish -c 'fisher update'

# NOTE: be sure to run base16-* before starting vim so it doesn't detonate

# setup vim
brew install neovim
stow -t ~ nvim
ln -sf /usr/local/bin/nvim ~/bin/vim
# NOTE: be sure to change login shell in iTerm2

# install rg
brew install ripgrep

# fzf and friends
brew install fzf bat
$(brew --prefix)/opt/fzf/install

# docker
brew install --cask docker

# setup go
brew install go
go install golang.org/x/tools/gopls@latest
# NOTE: restart fish to pick up new $PATH

# setup best font
brew tap homebrew/cask-fonts
brew install --cask font-iosevka
# NOTE: reboot for iTerm2 to pick it up

# configure git
./git/configure

# support holding hjkl
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# disable weird cmd-tab monitor selection
defaults write com.apple.Dock appswitcher-all-displays -bool true
