#!/usr/bin/env bash

set -e -u -x

# nix
sudo ln -sf $PWD/system.nix /etc/nixos/personal-configuration.nix

# nix home manager
mkdir -p ~/.config/nixpkgs
ln -sf $PWD/home.nix ~/.config/nixpkgs/home.nix

sudo nix-channel --add https://github.com/NixOS/nixos-hardware/archive/master.tar.gz nixos-hardware
