#!/usr/bin/env bash

set -e -u -x

cd $HOME

mkdir -p $HOME/.config
mkdir -p $HOME/.bin

### system-wide setup (requires reboot)

## bootstrap system-wide stuff all at once since it's slow and requires reboot
rpm-ostree install --idempotent \
  fish \
  distrobox \
  python3-pip \
  mako \
  docker

## not idempotent; do this manually
# rpm-ostree override remove firefox firefox-langpacks dunst

## (a reboot is required here on first setup)

## set up ntp
if ! timedatectl status | grep "NTP service: active" >/dev/null; then
  timedatectl set-ntp true
fi

## set up CLIs for waybar
if ! which nextmeeting >/dev/null; then
  sudo pip install nextmeeting gcalcli
fi

# install flathub
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo


### GUI apps

# use Webcord over Discord until they get off their ass and support Wayland or upgrade Electron
flatpak install --or-update io.github.spacingbat3.webcord # com.discordapp.Discord

# official Signal app
flatpak install --or-update org.signal.Signal

# install 1password from their official repo
if ! flatpak list | grep OnePassword >/dev/null; then
  flatpak install --or-update https://downloads.1password.com/linux/flatpak/1Password.flatpakref
fi

# Spotify
flatpak install --or-update com.spotify.Client

## Firefox
flatpak install --or-update org.mozilla.Firefox
# more video streaming codecs
flatpak install --or-update flathub org.freedesktop.Platform.ffmpeg-full

### CLI setup

# best prompt
if ! test -e $HOME/.bin/starship; then
  curl -sS https://starship.rs/install.sh | env BIN_DIR=$HOME/.bin sh
fi

# best font
if ! fc-list | grep 'Iosevka Term SS08' >/dev/null; then
  fontdir=/usr/local/share/fonts/IosevkaTermSS08
  sudo mkdir -p $fontdir
  wget https://github.com/be5invis/Iosevka/releases/download/v29.0.1/PkgTTF-IosevkaTermSS08-29.0.1.zip -O /tmp/iosevka.zip
  sudo unzip -d $fontdir /tmp/iosevka.zip
  sudo fc-cache -v
fi

# install each distro
for distro in distros/*; do
  name=$(basename $distro)
  if ! distrobox ls | grep $name >/dev/null; then
    distrobox create -n $name
  fi
  distrobox enter $name -- ./distros/$name
done

## Docker; manual steps needed for rpm-ostree
# see https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_unable_to_add_user_to_group
sudo sh -c "grep -E '^docker:' /usr/lib/group >> /etc/group"
sudo usermod -aG docker $(whoami)
# install docker-compose
if ! test -f .docker/cli-plugins/docker-compose; then
  mkdir -p .docker/cli-plugins
  wget https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-linux-x86_64 -O .docker/cli-plugins/docker-compose
  chmod +x .docker/cli-plugins/docker-compose
fi
