#!/bin/bash

set -e -u -x

cd $(dirname $0)

# simple config manager
brew install stow

# local executables dir
mkdir -p ~/bin

# setup fish
brew install fish
stow -t ~ fish
fish -c 'fisher update'
fish -c 'fisher install rose-pine/fish'

# install rg
brew install ripgrep

# setup go
brew install go

# configure git
./git/configure

# basic tooling
brew install wget

# install Rust + Cargo for Rust tools (e.g. win32yank)
brew install rust

# install python + uv stack
brew install python uv

# install wslu
if ! [ -e /etc/apt/sources.list.d/wslu.list ]; then
  sudo apt install gnupg2 apt-transport-https
  wget -O - https://pkg.wslutiliti.es/public.key | sudo gpg -o /usr/share/keyrings/wslu-archive-keyring.pgp --dearmor

  echo "deb [signed-by=/usr/share/keyrings/wslu-archive-keyring.pgp] https://pkg.wslutiliti.es/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") main" | sudo tee /etc/apt/sources.list.d/wslu.list

  sudo apt update
fi
sudo apt install wslu
