#!/bin/sh

set -e

xrandr --dpi 192
xrdb -merge -I$HOME $HOME/.Xresources-hidpi

xrandr \
  --output eDP1 --mode 2560x1600 --pos 0x0 \
  --output DP1 --off \
  --output DP2 --off \
  --output HDMI1 --off \
  --output HDMI2 --off \
  --output VIRTUAL1 --off
