#!/bin/sh

set -e

xrandr --dpi 96
xrdb -merge -I$HOME $HOME/.Xresources-lowdpi

xrandr \
  --output eDP1 --off \
  --output DP1 --off \
  --output DP2 --off \
  --output HDMI1 --off \
  --output HDMI2 --mode 2560x1440 --pos 0x0 --primary \
  --output VIRTUAL1 --off
