#!/bin/sh

set -e

xrandr --dpi 210
xrdb -merge -I$HOME $HOME/.Xresources-hidpi

hidpix=2560
hidpiy=1440

lowdpix=2560
lowdpiy=1440

scale=2

xrandr \
  --output DP-1 --off \
  --output DP-2 --off \
  --output eDP-1 --mode ${hidpix}x${hidpiy} \
    --primary \
  --output HDMI-1 --off \
  --output HDMI-2 --mode ${lowdpix}x${lowdpiy} \
    --right-of eDP-1 \
    --scale ${scale}x${scale} \
    --panning "$(expr $lowdpix \* $scale)x$(expr $lowdpiy \* $scale)+${hidpix}+0" \
